"""empty message

Revision ID: 051b69546678
Revises: 83e719e3ccc4
Create Date: 2021-04-16 22:55:04.049738

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '051b69546678'
down_revision = '83e719e3ccc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    op.add_column('role', sa.Column('userID', sa.String(length=100), nullable=False))
    op.create_foreign_key(None, 'role', 'usercredentials', ['userID'], ['userID'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='foreignkey')
    op.drop_column('role', 'userID')
    op.create_table('roles',
    sa.Column('role_name', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('userID', mysql.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['role_name'], ['role.role_name'], name='roles_ibfk_1'),
    sa.ForeignKeyConstraint(['userID'], ['usercredentials.userID'], name='roles_ibfk_2'),
    sa.PrimaryKeyConstraint('role_name', 'userID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
