"""empty message

Revision ID: 26329e714cd7
Revises: 
Create Date: 2021-03-19 12:21:43.613429

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '26329e714cd7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_account_typeID'), 'account', ['typeID'], unique=False)
    op.create_index(op.f('ix_asset_busID'), 'asset', ['busID'], unique=False)
    op.create_index(op.f('ix_con_service_cssiID'), 'con_service', ['cssiID'], unique=False)
    op.create_index(op.f('ix_con_service_sale_item_serviceID'), 'con_service_sale_item', ['serviceID'], unique=False)
    op.create_index(op.f('ix_credit_accountID'), 'credit', ['accountID'], unique=False)
    op.create_index(op.f('ix_creditvoucher_authBy'), 'creditvoucher', ['authBy'], unique=False)
    op.create_index(op.f('ix_creditvoucher_prepBy'), 'creditvoucher', ['prepBy'], unique=False)
    op.create_index(op.f('ix_currentasset_asset_id'), 'currentasset', ['asset_id'], unique=False)
    op.create_index(op.f('ix_currentasset_busID'), 'currentasset', ['busID'], unique=False)
    op.create_index(op.f('ix_currentliability_busID'), 'currentliability', ['busID'], unique=False)
    op.create_index(op.f('ix_currentliability_liab_id'), 'currentliability', ['liab_id'], unique=False)
    op.create_index(op.f('ix_debit_accountID'), 'debit', ['accountID'], unique=False)
    op.create_index(op.f('ix_financialstmtlinealias_fsStmtID'), 'financialstmtlinealias', ['fsStmtID'], unique=False)
    op.create_index(op.f('ix_financialstmtlineseq_fsStmtID'), 'financialstmtlineseq', ['fsStmtID'], unique=False)
    op.create_index(op.f('ix_financialstmtlineseq_fsStmtLineID'), 'financialstmtlineseq', ['fsStmtLineID'], unique=False)
    op.create_index(op.f('ix_invoice_custID'), 'invoice', ['custID'], unique=False)
    op.create_index(op.f('ix_liability_busID'), 'liability', ['busID'], unique=False)
    op.create_index(op.f('ix_longtermliability_busID'), 'longtermliability', ['busID'], unique=False)
    op.create_index(op.f('ix_longtermliability_liab_id'), 'longtermliability', ['liab_id'], unique=False)
    op.create_index(op.f('ix_noncurrentasset_asset_id'), 'noncurrentasset', ['asset_id'], unique=False)
    op.create_index(op.f('ix_noncurrentasset_busID'), 'noncurrentasset', ['busID'], unique=False)
    op.create_index(op.f('ix_order_busID'), 'order', ['busID'], unique=False)
    op.create_index(op.f('ix_order_custID'), 'order', ['custID'], unique=False)
    op.create_index(op.f('ix_order_invoiceID'), 'order', ['invoiceID'], unique=False)
    op.drop_column('product', 'baseUnit')
    op.create_index(op.f('ix_product_sale_item_customerID'), 'product_sale_item', ['customerID'], unique=False)
    op.create_index(op.f('ix_product_sale_item_prodID'), 'product_sale_item', ['prodID'], unique=False)
    op.create_index(op.f('ix_purchase_busID'), 'purchase', ['busID'], unique=False)
    op.create_index(op.f('ix_purchase_stmtID'), 'purchase', ['stmtID'], unique=False)
    op.create_index(op.f('ix_receipt_busID'), 'receipt', ['busID'], unique=False)
    op.create_index(op.f('ix_receipt_orderID'), 'receipt', ['orderID'], unique=False)
    op.create_index(op.f('ix_receiptdetails_orderID'), 'receiptdetails', ['orderID'], unique=False)
    op.create_index(op.f('ix_receiptdetails_prodID'), 'receiptdetails', ['prodID'], unique=False)
    op.create_index(op.f('ix_receiptdetails_serviceID'), 'receiptdetails', ['serviceID'], unique=False)
    op.create_index(op.f('ix_sale_customerID'), 'sale', ['customerID'], unique=False)
    op.create_index(op.f('ix_sale_receiptID'), 'sale', ['receiptID'], unique=False)
    op.add_column('service', sa.Column('serv_cost', sa.Integer(), nullable=True))
    op.drop_column('service', 'serv_price')
    op.create_index(op.f('ix_service_sale_item_userID'), 'service_sale_item', ['userID'], unique=False)
    op.create_index(op.f('ix_voucher_accountID'), 'voucher', ['accountID'], unique=False)
    op.create_index(op.f('ix_voucher_authBy'), 'voucher', ['authBy'], unique=False)
    op.create_index(op.f('ix_voucher_prepBy'), 'voucher', ['prepBy'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voucher_prepBy'), table_name='voucher')
    op.drop_index(op.f('ix_voucher_authBy'), table_name='voucher')
    op.drop_index(op.f('ix_voucher_accountID'), table_name='voucher')
    op.drop_index(op.f('ix_service_sale_item_userID'), table_name='service_sale_item')
    op.add_column('service', sa.Column('serv_price', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('service', 'serv_cost')
    op.drop_index(op.f('ix_sale_receiptID'), table_name='sale')
    op.drop_index(op.f('ix_sale_customerID'), table_name='sale')
    op.drop_index(op.f('ix_receiptdetails_serviceID'), table_name='receiptdetails')
    op.drop_index(op.f('ix_receiptdetails_prodID'), table_name='receiptdetails')
    op.drop_index(op.f('ix_receiptdetails_orderID'), table_name='receiptdetails')
    op.drop_index(op.f('ix_receipt_orderID'), table_name='receipt')
    op.drop_index(op.f('ix_receipt_busID'), table_name='receipt')
    op.drop_index(op.f('ix_purchase_stmtID'), table_name='purchase')
    op.drop_index(op.f('ix_purchase_busID'), table_name='purchase')
    op.drop_index(op.f('ix_product_sale_item_prodID'), table_name='product_sale_item')
    op.drop_index(op.f('ix_product_sale_item_customerID'), table_name='product_sale_item')
    op.add_column('product', sa.Column('baseUnit', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    op.drop_index(op.f('ix_order_invoiceID'), table_name='order')
    op.drop_index(op.f('ix_order_custID'), table_name='order')
    op.drop_index(op.f('ix_order_busID'), table_name='order')
    op.drop_index(op.f('ix_noncurrentasset_busID'), table_name='noncurrentasset')
    op.drop_index(op.f('ix_noncurrentasset_asset_id'), table_name='noncurrentasset')
    op.drop_index(op.f('ix_longtermliability_liab_id'), table_name='longtermliability')
    op.drop_index(op.f('ix_longtermliability_busID'), table_name='longtermliability')
    op.drop_index(op.f('ix_liability_busID'), table_name='liability')
    op.drop_index(op.f('ix_invoice_custID'), table_name='invoice')
    op.drop_index(op.f('ix_financialstmtlineseq_fsStmtLineID'), table_name='financialstmtlineseq')
    op.drop_index(op.f('ix_financialstmtlineseq_fsStmtID'), table_name='financialstmtlineseq')
    op.drop_index(op.f('ix_financialstmtlinealias_fsStmtID'), table_name='financialstmtlinealias')
    op.drop_index(op.f('ix_debit_accountID'), table_name='debit')
    op.drop_index(op.f('ix_currentliability_liab_id'), table_name='currentliability')
    op.drop_index(op.f('ix_currentliability_busID'), table_name='currentliability')
    op.drop_index(op.f('ix_currentasset_busID'), table_name='currentasset')
    op.drop_index(op.f('ix_currentasset_asset_id'), table_name='currentasset')
    op.drop_index(op.f('ix_creditvoucher_prepBy'), table_name='creditvoucher')
    op.drop_index(op.f('ix_creditvoucher_authBy'), table_name='creditvoucher')
    op.drop_index(op.f('ix_credit_accountID'), table_name='credit')
    op.drop_index(op.f('ix_con_service_sale_item_serviceID'), table_name='con_service_sale_item')
    op.drop_index(op.f('ix_con_service_cssiID'), table_name='con_service')
    op.drop_index(op.f('ix_asset_busID'), table_name='asset')
    op.drop_index(op.f('ix_account_typeID'), table_name='account')
    # ### end Alembic commands ###
