"""empty message

Revision ID: 2b28d43160cd
Revises: f84412ebe95d
Create Date: 2021-04-09 10:58:51.602858

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b28d43160cd'
down_revision = 'f84412ebe95d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usercredentials',
    sa.Column('userID', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('user_email', sa.String(length=50), nullable=False),
    sa.Column('user_password', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['userID'], ['user.userID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_email'),
    sa.UniqueConstraint('userID'),
    sa.UniqueConstraint('user_email')
    )
    op.drop_index('userID', table_name='credentials')
    op.drop_index('user_email', table_name='credentials')
    op.drop_table('credentials')
    op.drop_constraint('role_ibfk_1', 'role', type_='foreignkey')
    op.create_foreign_key(None, 'role', 'usercredentials', ['email'], ['user_email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='foreignkey')
    op.create_foreign_key('role_ibfk_1', 'role', 'credentials', ['email'], ['user_email'])
    op.create_table('credentials',
    sa.Column('userID', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('user_email', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('user_password', mysql.VARCHAR(length=255), nullable=True),
    sa.CheckConstraint('(`active` in (0,1))', name='credentials_chk_1'),
    sa.ForeignKeyConstraint(['userID'], ['user.userID'], name='credentials_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_email'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('user_email', 'credentials', ['user_email'], unique=True)
    op.create_index('userID', 'credentials', ['userID'], unique=True)
    op.drop_table('usercredentials')
    # ### end Alembic commands ###
