"""empty message

Revision ID: 4284dbef474e
Revises: 52ee97e8dcf2
Create Date: 2021-04-29 17:03:15.570251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4284dbef474e'
down_revision = '52ee97e8dcf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'financialstmt', ['fs_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'financialstmt', type_='unique')
    # ### end Alembic commands ###
