"""empty message

Revision ID: 4e5d37ab9fd7
Revises: 19aba07e041a
Create Date: 2021-04-05 02:20:48.700923

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4e5d37ab9fd7'
down_revision = '19aba07e041a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credentials', sa.Column('user_email', sa.String(length=50), nullable=False))
    op.drop_column('credentials', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credentials', sa.Column('email', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('credentials', 'user_email')
    # ### end Alembic commands ###
