"""empty message

Revision ID: 65075912959a
Revises: 6d07eff918d4
Create Date: 2021-05-16 07:43:35.815236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65075912959a'
down_revision = '6d07eff918d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genledger', sa.Column('test', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('genledger', 'test')
    # ### end Alembic commands ###
