"""empty message

Revision ID: 69ab38938a28
Revises: 03d598e25cce
Create Date: 2021-04-29 21:02:46.024792

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '69ab38938a28'
down_revision = '03d598e25cce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('financialstmtline', 'fstmtID',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('financialstmtline', 'fstmtID',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
