"""empty message

Revision ID: 701029077920
Revises: 1d4afa8d7965
Create Date: 2021-05-18 05:58:59.162403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '701029077920'
down_revision = '1d4afa8d7965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('custorder_ibfk_3', 'custorder', type_='foreignkey')
    op.create_foreign_key(None, 'custorder', 'invoice', ['invoiceID'], ['invoiceID'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'custorder', type_='foreignkey')
    op.create_foreign_key('custorder_ibfk_3', 'custorder', 'invoice', ['invoiceID'], ['custID'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
