"""empty message

Revision ID: 8688e237514b
Revises: 65075912959a
Create Date: 2021-05-16 07:44:37.690622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8688e237514b'
down_revision = '65075912959a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genledger', sa.Column('year', sa.String(length=15), nullable=True))
    op.drop_column('genledger', 'Year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genledger', sa.Column('Year', sa.DATE(), nullable=True))
    op.drop_column('genledger', 'year')
    # ### end Alembic commands ###
