"""empty message

Revision ID: 90dc1f64be25
Revises: 3f84fde3399b
Create Date: 2021-04-20 19:54:46.439512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90dc1f64be25'
down_revision = '3f84fde3399b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('grade', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'grade')
    # ### end Alembic commands ###
