"""empty message

Revision ID: 94ef98ced171
Revises: a08131bc52e8
Create Date: 2021-04-22 13:47:32.811807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94ef98ced171'
down_revision = 'a08131bc52e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('con_service', sa.Column('busID', sa.String(length=100), nullable=True))
    op.add_column('con_service', sa.Column('image', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_con_service_busID'), 'con_service', ['busID'], unique=False)
    op.create_foreign_key(None, 'con_service', 'business', ['busID'], ['busID'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('invoice', sa.Column('busID', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_invoice_busID'), 'invoice', ['busID'], unique=False)
    op.create_foreign_key(None, 'invoice', 'business', ['busID'], ['busID'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('product', sa.Column('busID', sa.String(length=100), nullable=True))
    op.add_column('product', sa.Column('grade', sa.String(length=5), nullable=True))
    op.add_column('product', sa.Column('image', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_product_busID'), 'product', ['busID'], unique=False)
    op.create_foreign_key(None, 'product', 'business', ['busID'], ['busID'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('service', sa.Column('busID', sa.String(length=100), nullable=True))
    op.add_column('service', sa.Column('image', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_service_busID'), 'service', ['busID'], unique=False)
    op.create_foreign_key(None, 'service', 'business', ['busID'], ['busID'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service', type_='foreignkey')
    op.drop_index(op.f('ix_service_busID'), table_name='service')
    op.drop_column('service', 'image')
    op.drop_column('service', 'busID')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_index(op.f('ix_product_busID'), table_name='product')
    op.drop_column('product', 'image')
    op.drop_column('product', 'grade')
    op.drop_column('product', 'busID')
    op.drop_constraint(None, 'invoice', type_='foreignkey')
    op.drop_index(op.f('ix_invoice_busID'), table_name='invoice')
    op.drop_column('invoice', 'busID')
    op.drop_constraint(None, 'con_service', type_='foreignkey')
    op.drop_index(op.f('ix_con_service_busID'), table_name='con_service')
    op.drop_column('con_service', 'image')
    op.drop_column('con_service', 'busID')
    # ### end Alembic commands ###
