"""empty message

Revision ID: 9cf4c2c14c03
Revises: 5c869be3b7f0
Create Date: 2021-05-12 18:27:41.025115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cf4c2c14c03'
down_revision = '5c869be3b7f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currentliability', sa.Column('loanPeriods', sa.Integer(), nullable=True))
    op.drop_column('currentliability', 'dueDATE')
    op.add_column('longtermliability', sa.Column('loanPeriods', sa.Integer(), nullable=True))
    op.drop_column('longtermliability', 'dueDATE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('longtermliability', sa.Column('dueDATE', sa.DATE(), nullable=True))
    op.drop_column('longtermliability', 'loanPeriods')
    op.add_column('currentliability', sa.Column('dueDATE', sa.DATE(), nullable=True))
    op.drop_column('currentliability', 'loanPeriods')
    # ### end Alembic commands ###
