"""empty message

Revision ID: a09ae922beec
Revises: 
Create Date: 2021-03-25 00:32:49.650696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a09ae922beec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business',
    sa.Column('busID', sa.Integer(), nullable=False),
    sa.Column('busName', sa.String(length=100), nullable=True),
    sa.Column('busemail', sa.String(length=255), nullable=True),
    sa.Column('busaddress', sa.String(length=100), nullable=True),
    sa.Column('telephone', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('busID'),
    sa.UniqueConstraint('busID')
    )
    op.create_table('customer',
    sa.Column('custID', sa.String(length=10), nullable=False),
    sa.Column('fname', sa.String(length=100), nullable=True),
    sa.Column('lname', sa.String(length=100), nullable=True),
    sa.Column('trn', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('custID')
    )
    op.create_table('expense',
    sa.Column('expenseID', sa.String(length=10), nullable=False),
    sa.Column('extype', sa.String(length=100), nullable=True),
    sa.Column('exname', sa.String(length=100), nullable=True),
    sa.Column('DATEIncurred', sa.Date(), nullable=True),
    sa.Column('expenseAmt', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('expenseID'),
    sa.UniqueConstraint('expenseID')
    )
    op.create_table('financialstmt',
    sa.Column('stmtID', sa.String(length=10), nullable=False),
    sa.Column('fs_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('stmtID'),
    sa.UniqueConstraint('stmtID')
    )
    op.create_table('financialstmtline',
    sa.Column('lineID', sa.Integer(), nullable=False),
    sa.Column('line_name', sa.String(length=50), nullable=True),
    sa.Column('lineDesc', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('lineID'),
    sa.UniqueConstraint('lineID')
    )
    op.create_table('product',
    sa.Column('prodID', sa.String(length=10), nullable=False),
    sa.Column('prodName', sa.String(length=100), nullable=True),
    sa.Column('unit_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('Unit', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('limitedTime', sa.DateTime(), nullable=True),
    sa.Column('taxPercent', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('prodStatus', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('prodID')
    )
    op.create_table('service',
    sa.Column('serviceID', sa.String(length=11), nullable=False),
    sa.Column('serv_name', sa.String(length=11), nullable=True),
    sa.Column('serv_cost', sa.Integer(), nullable=True),
    sa.Column('taxPercent', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('in_season', sa.String(length=11), nullable=True),
    sa.PrimaryKeyConstraint('serviceID')
    )
    op.create_table('user',
    sa.Column('userID', sa.String(length=5), nullable=False),
    sa.Column('fname', sa.String(length=25), nullable=True),
    sa.Column('lname', sa.String(length=25), nullable=True),
    sa.Column('user_address', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('userID'),
    sa.UniqueConstraint('userID')
    )
    op.create_table('asset',
    sa.Column('asset_id', sa.String(length=10), nullable=False),
    sa.Column('a_name', sa.String(length=100), nullable=True),
    sa.Column('lifeSpan', sa.Integer(), nullable=True),
    sa.Column('a_type', sa.String(length=100), nullable=True),
    sa.Column('acquisDATE', sa.Date(), nullable=True),
    sa.Column('a_value', sa.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('busID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['busID'], ['business.busID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_index(op.f('ix_asset_busID'), 'asset', ['busID'], unique=False)
    op.create_table('con_service_sale_item',
    sa.Column('cssiID', sa.String(length=11), nullable=False),
    sa.Column('quantitySold', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Integer(), nullable=True),
    sa.Column('serv_price', sa.Integer(), nullable=True),
    sa.Column('taxAmt', sa.Integer(), nullable=True),
    sa.Column('serviceID', sa.String(length=11), nullable=True),
    sa.Column('starttime', sa.DateTime(), nullable=True),
    sa.Column('endtime', sa.DateTime(), nullable=True),
    sa.Column('prolong_period', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['serviceID'], ['service.serviceID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cssiID')
    )
    op.create_index(op.f('ix_con_service_sale_item_serviceID'), 'con_service_sale_item', ['serviceID'], unique=False)
    op.create_table('credentials',
    sa.Column('userID', sa.String(length=5), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('user_password', sa.String(length=255), nullable=True),
    sa.Column('pass_salt', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['userID'], ['user.userID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('userID')
    )
    op.create_table('financialstmtdesc',
    sa.Column('fStmtDescID', sa.Integer(), nullable=False),
    sa.Column('companyID', sa.Integer(), nullable=False),
    sa.Column('fsLineID', sa.Integer(), nullable=False),
    sa.Column('fiscalPeriod', sa.Date(), nullable=True),
    sa.Column('fillingDATE', sa.Date(), nullable=True),
    sa.Column('fiscalYear', sa.Integer(), nullable=True),
    sa.Column('startDATE', sa.Date(), nullable=True),
    sa.Column('endDATE', sa.Date(), nullable=True),
    sa.Column('unit', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['companyID'], ['business.busID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fsLineID'], ['financialstmtline.lineID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fStmtDescID', 'companyID', 'fsLineID'),
    sa.UniqueConstraint('companyID'),
    sa.UniqueConstraint('fStmtDescID'),
    sa.UniqueConstraint('fsLineID')
    )
    op.create_table('financialstmtlinealias',
    sa.Column('lineID', sa.Integer(), nullable=False),
    sa.Column('fsStmtID', sa.String(length=10), nullable=False),
    sa.Column('aliasID', sa.Integer(), nullable=False),
    sa.Column('lineAlias', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['fsStmtID'], ['financialstmt.stmtID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lineID'], ['financialstmtline.lineID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lineID', 'aliasID'),
    sa.UniqueConstraint('aliasID'),
    sa.UniqueConstraint('lineID')
    )
    op.create_index(op.f('ix_financialstmtlinealias_fsStmtID'), 'financialstmtlinealias', ['fsStmtID'], unique=False)
    op.create_table('financialstmtlineseq',
    sa.Column('lineSeqID', sa.Integer(), nullable=False),
    sa.Column('fsStmtID', sa.String(length=10), nullable=False),
    sa.Column('fsStmtLineID', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fsStmtID'], ['financialstmt.stmtID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fsStmtLineID'], ['financialstmtline.lineID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lineSeqID', 'fsStmtID', 'fsStmtLineID')
    )
    op.create_index(op.f('ix_financialstmtlineseq_fsStmtID'), 'financialstmtlineseq', ['fsStmtID'], unique=False)
    op.create_index(op.f('ix_financialstmtlineseq_fsStmtLineID'), 'financialstmtlineseq', ['fsStmtLineID'], unique=False)
    op.create_table('invoice',
    sa.Column('invoiceID', sa.String(length=10), nullable=False),
    sa.Column('custID', sa.String(length=10), nullable=True),
    sa.Column('invoice_DATE', sa.Date(), nullable=True),
    sa.Column('tax_tot', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['custID'], ['customer.custID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('invoiceID')
    )
    op.create_index(op.f('ix_invoice_custID'), 'invoice', ['custID'], unique=False)
    op.create_table('liability',
    sa.Column('liab_id', sa.String(length=5), nullable=False),
    sa.Column('liab_type', sa.String(length=100), nullable=True),
    sa.Column('liab_name', sa.String(length=100), nullable=True),
    sa.Column('Amt_owed', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('borw_DATE', sa.Date(), nullable=True),
    sa.Column('loan_period', sa.Integer(), nullable=True),
    sa.Column('busID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['busID'], ['business.busID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('liab_id'),
    sa.UniqueConstraint('liab_id')
    )
    op.create_index(op.f('ix_liability_busID'), 'liability', ['busID'], unique=False)
    op.create_table('product_sale_item',
    sa.Column('psiID', sa.Integer(), nullable=False),
    sa.Column('customerID', sa.String(length=10), nullable=True),
    sa.Column('timePaid', sa.DateTime(), nullable=True),
    sa.Column('timeCreated', sa.DateTime(), nullable=True),
    sa.Column('saleAmt', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('saleAmtPaid', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('SaleStatus', sa.String(length=25), nullable=True),
    sa.Column('quantitySold', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('unit_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('prodID', sa.String(length=10), nullable=True),
    sa.Column('taxAmt', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['customerID'], ['customer.custID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prodID'], ['product.prodID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('psiID')
    )
    op.create_index(op.f('ix_product_sale_item_customerID'), 'product_sale_item', ['customerID'], unique=False)
    op.create_index(op.f('ix_product_sale_item_prodID'), 'product_sale_item', ['prodID'], unique=False)
    op.create_table('purchase',
    sa.Column('purchaseID', sa.String(length=10), nullable=False),
    sa.Column('p_DATE', sa.Date(), nullable=True),
    sa.Column('p_item', sa.String(length=100), nullable=True),
    sa.Column('p_quantity', sa.Integer(), nullable=True),
    sa.Column('p_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('busID', sa.Integer(), nullable=True),
    sa.Column('stmtID', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['busID'], ['business.busID'], ),
    sa.ForeignKeyConstraint(['stmtID'], ['financialstmt.stmtID'], ),
    sa.PrimaryKeyConstraint('purchaseID'),
    sa.UniqueConstraint('purchaseID')
    )
    op.create_index(op.f('ix_purchase_busID'), 'purchase', ['busID'], unique=False)
    op.create_index(op.f('ix_purchase_stmtID'), 'purchase', ['stmtID'], unique=False)
    op.create_table('service_sale_item',
    sa.Column('ssiID', sa.String(length=11), nullable=False),
    sa.Column('serv_price', sa.Integer(), nullable=True),
    sa.Column('taxAmt', sa.Integer(), nullable=True),
    sa.Column('serviceID', sa.String(length=11), nullable=True),
    sa.Column('userID', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['ssiID'], ['service.serviceID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userID'], ['user.userID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ssiID')
    )
    op.create_index(op.f('ix_service_sale_item_userID'), 'service_sale_item', ['userID'], unique=False)
    op.create_table('stock',
    sa.Column('prodID', sa.String(length=10), nullable=False),
    sa.Column('inStock', sa.String(length=10), nullable=True),
    sa.Column('lastUpdateTime', sa.DateTime(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('threshold', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prodID'], ['product.prodID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prodID')
    )
    op.create_table('con_service',
    sa.Column('serviceID', sa.String(length=11), nullable=False),
    sa.Column('serv_name', sa.String(length=11), nullable=True),
    sa.Column('serv_uprice', sa.Integer(), nullable=True),
    sa.Column('basic_unit', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('d_prolongperiod', sa.DateTime(), nullable=True),
    sa.Column('taxPercent', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('in_season', sa.String(length=11), nullable=True),
    sa.Column('cssiID', sa.String(length=11), nullable=True),
    sa.ForeignKeyConstraint(['cssiID'], ['con_service_sale_item.cssiID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('serviceID')
    )
    op.create_index(op.f('ix_con_service_cssiID'), 'con_service', ['cssiID'], unique=False)
    op.create_table('currentasset',
    sa.Column('asset_id', sa.String(length=10), nullable=True),
    sa.Column('a_name', sa.String(length=100), nullable=True),
    sa.Column('lifeSpan', sa.Integer(), nullable=True),
    sa.Column('a_type', sa.String(length=100), nullable=True),
    sa.Column('acquisDATE', sa.Date(), nullable=True),
    sa.Column('a_value', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('ca_id', sa.String(length=10), nullable=False),
    sa.Column('busID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.asset_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['busID'], ['business.busID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ca_id')
    )
    op.create_index(op.f('ix_currentasset_asset_id'), 'currentasset', ['asset_id'], unique=False)
    op.create_index(op.f('ix_currentasset_busID'), 'currentasset', ['busID'], unique=False)
    op.create_table('currentliability',
    sa.Column('liab_id', sa.String(length=5), nullable=True),
    sa.Column('cliab_id', sa.String(length=10), nullable=False),
    sa.Column('liab_type', sa.String(length=100), nullable=True),
    sa.Column('liab_name', sa.String(length=100), nullable=True),
    sa.Column('Amt_owed', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('borw_DATE', sa.Date(), nullable=True),
    sa.Column('loan_period', sa.Integer(), nullable=True),
    sa.Column('busID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['busID'], ['business.busID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['liab_id'], ['liability.liab_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cliab_id'),
    sa.UniqueConstraint('cliab_id')
    )
    op.create_index(op.f('ix_currentliability_busID'), 'currentliability', ['busID'], unique=False)
    op.create_index(op.f('ix_currentliability_liab_id'), 'currentliability', ['liab_id'], unique=False)
    op.create_table('longtermliability',
    sa.Column('liab_id', sa.String(length=5), nullable=True),
    sa.Column('Itliab_id', sa.String(length=10), nullable=False),
    sa.Column('liab_type', sa.String(length=100), nullable=True),
    sa.Column('liab_name', sa.String(length=100), nullable=True),
    sa.Column('Amt_owed', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('borw_DATE', sa.Date(), nullable=True),
    sa.Column('loan_period', sa.Integer(), nullable=True),
    sa.Column('busID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['busID'], ['business.busID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['liab_id'], ['liability.liab_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Itliab_id'),
    sa.UniqueConstraint('Itliab_id')
    )
    op.create_index(op.f('ix_longtermliability_busID'), 'longtermliability', ['busID'], unique=False)
    op.create_index(op.f('ix_longtermliability_liab_id'), 'longtermliability', ['liab_id'], unique=False)
    op.create_table('noncurrentasset',
    sa.Column('asset_id', sa.String(length=10), nullable=True),
    sa.Column('a_name', sa.String(length=100), nullable=True),
    sa.Column('lifeSpan', sa.Integer(), nullable=True),
    sa.Column('a_type', sa.String(length=100), nullable=True),
    sa.Column('acquisDATE', sa.Date(), nullable=True),
    sa.Column('a_value', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('nca_id', sa.String(length=10), nullable=False),
    sa.Column('AccumDep', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('disposalAmt', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('depType', sa.String(length=100), nullable=True),
    sa.Column('busID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.asset_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['busID'], ['business.busID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('nca_id')
    )
    op.create_index(op.f('ix_noncurrentasset_asset_id'), 'noncurrentasset', ['asset_id'], unique=False)
    op.create_index(op.f('ix_noncurrentasset_busID'), 'noncurrentasset', ['busID'], unique=False)
    op.create_table('order',
    sa.Column('orderID', sa.String(length=10), nullable=False),
    sa.Column('order_tot', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('order_DATE', sa.Date(), nullable=True),
    sa.Column('custID', sa.String(length=10), nullable=True),
    sa.Column('invoiceID', sa.String(length=10), nullable=True),
    sa.Column('busID', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['busID'], ['business.busID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['custID'], ['customer.custID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoiceID'], ['invoice.custID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('orderID')
    )
    op.create_index(op.f('ix_order_busID'), 'order', ['busID'], unique=False)
    op.create_index(op.f('ix_order_custID'), 'order', ['custID'], unique=False)
    op.create_index(op.f('ix_order_invoiceID'), 'order', ['invoiceID'], unique=False)
    op.create_table('orderdetails',
    sa.Column('orderID', sa.String(length=10), nullable=False),
    sa.Column('detailsID', sa.String(length=10), nullable=False),
    sa.Column('prodID', sa.String(length=10), nullable=True),
    sa.Column('serviceID', sa.String(length=10), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('order_tot', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['orderID'], ['order.orderID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('orderID', 'detailsID')
    )
    op.create_table('receipt',
    sa.Column('receiptID', sa.String(length=10), nullable=False),
    sa.Column('orderID', sa.String(length=10), nullable=True),
    sa.Column('busID', sa.Integer(), nullable=True),
    sa.Column('DATE_issued', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['busID'], ['business.busID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['orderID'], ['order.orderID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('receiptID')
    )
    op.create_index(op.f('ix_receipt_busID'), 'receipt', ['busID'], unique=False)
    op.create_index(op.f('ix_receipt_orderID'), 'receipt', ['orderID'], unique=False)
    op.create_table('receiptdetails',
    sa.Column('receiptID', sa.String(length=10), nullable=False),
    sa.Column('rdetailsID', sa.String(length=10), nullable=False),
    sa.Column('orderID', sa.String(length=10), nullable=True),
    sa.Column('prodID', sa.String(length=10), nullable=True),
    sa.Column('serviceID', sa.String(length=11), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('order_tot', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['orderID'], ['order.orderID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prodID'], ['product.prodID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receiptID'], ['receipt.receiptID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['serviceID'], ['service.serviceID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rdetailsID'),
    sa.UniqueConstraint('receiptID')
    )
    op.create_index(op.f('ix_receiptdetails_orderID'), 'receiptdetails', ['orderID'], unique=False)
    op.create_index(op.f('ix_receiptdetails_prodID'), 'receiptdetails', ['prodID'], unique=False)
    op.create_index(op.f('ix_receiptdetails_serviceID'), 'receiptdetails', ['serviceID'], unique=False)
    op.create_table('sale',
    sa.Column('saleID', sa.String(length=11), nullable=False),
    sa.Column('customerID', sa.String(length=10), nullable=True),
    sa.Column('timePaid', sa.DateTime(), nullable=True),
    sa.Column('timeCreated', sa.DateTime(), nullable=True),
    sa.Column('saleAmt', sa.Integer(), nullable=True),
    sa.Column('saleAmtPaid', sa.Integer(), nullable=True),
    sa.Column('SaleStatus', sa.String(length=11), nullable=True),
    sa.Column('receiptID', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['customerID'], ['customer.custID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receiptID'], ['receipt.receiptID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('saleID')
    )
    op.create_index(op.f('ix_sale_customerID'), 'sale', ['customerID'], unique=False)
    op.create_index(op.f('ix_sale_receiptID'), 'sale', ['receiptID'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_receiptID'), table_name='sale')
    op.drop_index(op.f('ix_sale_customerID'), table_name='sale')
    op.drop_table('sale')
    op.drop_index(op.f('ix_receiptdetails_serviceID'), table_name='receiptdetails')
    op.drop_index(op.f('ix_receiptdetails_prodID'), table_name='receiptdetails')
    op.drop_index(op.f('ix_receiptdetails_orderID'), table_name='receiptdetails')
    op.drop_table('receiptdetails')
    op.drop_index(op.f('ix_receipt_orderID'), table_name='receipt')
    op.drop_index(op.f('ix_receipt_busID'), table_name='receipt')
    op.drop_table('receipt')
    op.drop_table('orderdetails')
    op.drop_index(op.f('ix_order_invoiceID'), table_name='order')
    op.drop_index(op.f('ix_order_custID'), table_name='order')
    op.drop_index(op.f('ix_order_busID'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_noncurrentasset_busID'), table_name='noncurrentasset')
    op.drop_index(op.f('ix_noncurrentasset_asset_id'), table_name='noncurrentasset')
    op.drop_table('noncurrentasset')
    op.drop_index(op.f('ix_longtermliability_liab_id'), table_name='longtermliability')
    op.drop_index(op.f('ix_longtermliability_busID'), table_name='longtermliability')
    op.drop_table('longtermliability')
    op.drop_index(op.f('ix_currentliability_liab_id'), table_name='currentliability')
    op.drop_index(op.f('ix_currentliability_busID'), table_name='currentliability')
    op.drop_table('currentliability')
    op.drop_index(op.f('ix_currentasset_busID'), table_name='currentasset')
    op.drop_index(op.f('ix_currentasset_asset_id'), table_name='currentasset')
    op.drop_table('currentasset')
    op.drop_index(op.f('ix_con_service_cssiID'), table_name='con_service')
    op.drop_table('con_service')
    op.drop_table('stock')
    op.drop_index(op.f('ix_service_sale_item_userID'), table_name='service_sale_item')
    op.drop_table('service_sale_item')
    op.drop_index(op.f('ix_purchase_stmtID'), table_name='purchase')
    op.drop_index(op.f('ix_purchase_busID'), table_name='purchase')
    op.drop_table('purchase')
    op.drop_index(op.f('ix_product_sale_item_prodID'), table_name='product_sale_item')
    op.drop_index(op.f('ix_product_sale_item_customerID'), table_name='product_sale_item')
    op.drop_table('product_sale_item')
    op.drop_index(op.f('ix_liability_busID'), table_name='liability')
    op.drop_table('liability')
    op.drop_index(op.f('ix_invoice_custID'), table_name='invoice')
    op.drop_table('invoice')
    op.drop_index(op.f('ix_financialstmtlineseq_fsStmtLineID'), table_name='financialstmtlineseq')
    op.drop_index(op.f('ix_financialstmtlineseq_fsStmtID'), table_name='financialstmtlineseq')
    op.drop_table('financialstmtlineseq')
    op.drop_index(op.f('ix_financialstmtlinealias_fsStmtID'), table_name='financialstmtlinealias')
    op.drop_table('financialstmtlinealias')
    op.drop_table('financialstmtdesc')
    op.drop_table('credentials')
    op.drop_index(op.f('ix_con_service_sale_item_serviceID'), table_name='con_service_sale_item')
    op.drop_table('con_service_sale_item')
    op.drop_index(op.f('ix_asset_busID'), table_name='asset')
    op.drop_table('asset')
    op.drop_table('user')
    op.drop_table('service')
    op.drop_table('product')
    op.drop_table('financialstmtline')
    op.drop_table('financialstmt')
    op.drop_table('expense')
    op.drop_table('customer')
    op.drop_table('business')
    # ### end Alembic commands ###
