"""empty message

Revision ID: ac3be69a2b3e
Revises: 9cf4c2c14c03
Create Date: 2021-05-12 22:35:05.685408

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac3be69a2b3e'
down_revision = '9cf4c2c14c03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currentasset', sa.Column('lifeSpan', sa.Integer(), nullable=True))
    op.add_column('noncurrentasset', sa.Column('totalUnits', sa.Integer(), nullable=True))
    op.drop_column('noncurrentasset', 'accumDep')
    op.drop_column('noncurrentasset', 'disposalAmt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noncurrentasset', sa.Column('disposalAmt', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('noncurrentasset', sa.Column('accumDep', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    op.drop_column('noncurrentasset', 'totalUnits')
    op.drop_column('currentasset', 'lifeSpan')
    # ### end Alembic commands ###
