"""empty message

Revision ID: b13d50832dce
Revises: c6b4e132a9aa
Create Date: 2021-05-15 14:39:00.928119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b13d50832dce'
down_revision = 'c6b4e132a9aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('prodType', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'prodType')
    # ### end Alembic commands ###
