"""empty message

Revision ID: b93c50f539ba
Revises: 159c749c4cfd
Create Date: 2021-04-17 15:18:12.735877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b93c50f539ba'
down_revision = '159c749c4cfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('userID', table_name='role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('userID', 'role', ['userID'], unique=True)
    # ### end Alembic commands ###
