"""empty message

Revision ID: c6b4e132a9aa
Revises: ac3be69a2b3e
Create Date: 2021-05-15 14:38:04.403550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6b4e132a9aa'
down_revision = 'ac3be69a2b3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customerpayment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cusID', sa.Integer(), nullable=True),
    sa.Column('orderID', sa.Integer(), nullable=True),
    sa.Column('receipt', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['cusID'], ['customer.custID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['orderID'], ['custorder.orderID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customerpayment_cusID'), 'customerpayment', ['cusID'], unique=False)
    op.create_index(op.f('ix_customerpayment_orderID'), 'customerpayment', ['orderID'], unique=False)
    op.add_column('customer', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('customer', sa.Column('busID', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_customer_busID'), 'customer', ['busID'], unique=False)
    op.create_foreign_key(None, 'customer', 'business', ['busID'], ['busID'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.drop_index(op.f('ix_customer_busID'), table_name='customer')
    op.drop_column('customer', 'busID')
    op.drop_column('customer', 'address')
    op.drop_index(op.f('ix_customerpayment_orderID'), table_name='customerpayment')
    op.drop_index(op.f('ix_customerpayment_cusID'), table_name='customerpayment')
    op.drop_table('customerpayment')
    # ### end Alembic commands ###
