"""empty message

Revision ID: c7becceb8a76
Revises: 051b69546678
Create Date: 2021-04-16 23:14:54.295443

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7becceb8a76'
down_revision = '051b69546678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('date_joined', sa.DateTime(), nullable=True))
    op.drop_column('business', 'date_added')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('date_added', mysql.DATETIME(), nullable=True))
    op.drop_column('business', 'date_joined')
    # ### end Alembic commands ###
