"""empty message

Revision ID: d5044637856c
Revises: 21add9f57d58
Create Date: 2021-05-18 00:55:50.737473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5044637856c'
down_revision = '21add9f57d58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'con_service', 'business', ['busID'], ['busID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'con_service', 'con_service_sale_item', ['cssiID'], ['cssiID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'con_service_sale_item', 'service', ['serviceID'], ['serviceID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'currentasset', 'business', ['busID'], ['busID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'currentliability', 'business', ['busID'], ['busID'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('custorder', sa.Column('note', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'custorder', 'customer', ['custID'], ['custID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'custorder', 'business', ['busID'], ['busID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'custorder', 'invoice', ['invoiceID'], ['custID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'equity', 'business', ['busID'], ['busID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'financialstmtdesc', 'business', ['busID'], ['busID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'financialstmtdesc', 'financialstmtline', ['fsLineID'], ['lineID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'financialstmtlinealias', 'financialstmtline', ['lineID'], ['lineID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'financialstmtlineseq', 'financialstmt', ['fsStmtID'], ['stmtID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'financialstmtlineseq', 'financialstmtline', ['fsStmtLineID'], ['lineID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'genledger', 'business', ['busID'], ['busID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'invoice', 'customer', ['custID'], ['custID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'invoice', 'business', ['busID'], ['busID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'ledgerdetails', 'business', ['busID'], ['busID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'ledgerdetails', 'genledger', ['ledgerID'], ['ledgerID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'longtermliability', 'business', ['busID'], ['busID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'noncurrentasset', 'business', ['busID'], ['busID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'nonopex', 'business', ['busID'], ['busID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'nonoprev', 'business', ['busID'], ['busID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'opex', 'business', ['busID'], ['busID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'oprev', 'business', ['busID'], ['busID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'orderdetails', 'custorder', ['orderID'], ['orderID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'product', 'business', ['busID'], ['busID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'product_sale_item', 'product', ['prodID'], ['prodID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'product_sale_item', 'customer', ['customerID'], ['custID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'receipt', 'custorder', ['orderID'], ['orderID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'receipt', 'business', ['busID'], ['busID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'receiptdetails', 'service', ['serviceID'], ['serviceID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'receiptdetails', 'product', ['prodID'], ['prodID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'receiptdetails', 'custorder', ['orderID'], ['orderID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'receiptdetails', 'receipt', ['receiptID'], ['receiptID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'role', 'usercredentials', ['userID'], ['userID'])
    op.create_foreign_key(None, 'sale', 'receipt', ['receiptID'], ['receiptID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'sale', 'customer', ['customerID'], ['custID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'service', 'business', ['busID'], ['busID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'service_sale_item', 'service', ['serviceID'], ['serviceID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'service_sale_item', 'user', ['userID'], ['userID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'stock', 'product', ['prodID'], ['prodID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'usercredentials', 'business', ['busID'], ['busID'])
    op.create_foreign_key(None, 'usercredentials', 'user', ['userID'], ['userID'])
    op.create_foreign_key(None, 'websitedrag', 'websitedetails', ['section_detail'], ['section_detail'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'websitedrag', type_='foreignkey')
    op.drop_constraint(None, 'usercredentials', type_='foreignkey')
    op.drop_constraint(None, 'usercredentials', type_='foreignkey')
    op.drop_constraint(None, 'stock', type_='foreignkey')
    op.drop_constraint(None, 'service_sale_item', type_='foreignkey')
    op.drop_constraint(None, 'service_sale_item', type_='foreignkey')
    op.drop_constraint(None, 'service', type_='foreignkey')
    op.drop_constraint(None, 'sale', type_='foreignkey')
    op.drop_constraint(None, 'sale', type_='foreignkey')
    op.drop_constraint(None, 'role', type_='foreignkey')
    op.drop_constraint(None, 'receiptdetails', type_='foreignkey')
    op.drop_constraint(None, 'receiptdetails', type_='foreignkey')
    op.drop_constraint(None, 'receiptdetails', type_='foreignkey')
    op.drop_constraint(None, 'receiptdetails', type_='foreignkey')
    op.drop_constraint(None, 'receipt', type_='foreignkey')
    op.drop_constraint(None, 'receipt', type_='foreignkey')
    op.drop_constraint(None, 'product_sale_item', type_='foreignkey')
    op.drop_constraint(None, 'product_sale_item', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'orderdetails', type_='foreignkey')
    op.drop_constraint(None, 'oprev', type_='foreignkey')
    op.drop_constraint(None, 'opex', type_='foreignkey')
    op.drop_constraint(None, 'nonoprev', type_='foreignkey')
    op.drop_constraint(None, 'nonopex', type_='foreignkey')
    op.drop_constraint(None, 'noncurrentasset', type_='foreignkey')
    op.drop_constraint(None, 'longtermliability', type_='foreignkey')
    op.drop_constraint(None, 'ledgerdetails', type_='foreignkey')
    op.drop_constraint(None, 'ledgerdetails', type_='foreignkey')
    op.drop_constraint(None, 'invoice', type_='foreignkey')
    op.drop_constraint(None, 'invoice', type_='foreignkey')
    op.drop_constraint(None, 'genledger', type_='foreignkey')
    op.drop_constraint(None, 'financialstmtlineseq', type_='foreignkey')
    op.drop_constraint(None, 'financialstmtlineseq', type_='foreignkey')
    op.drop_constraint(None, 'financialstmtlinealias', type_='foreignkey')
    op.drop_constraint(None, 'financialstmtdesc', type_='foreignkey')
    op.drop_constraint(None, 'financialstmtdesc', type_='foreignkey')
    op.drop_constraint(None, 'equity', type_='foreignkey')
    op.drop_constraint(None, 'custorder', type_='foreignkey')
    op.drop_constraint(None, 'custorder', type_='foreignkey')
    op.drop_constraint(None, 'custorder', type_='foreignkey')
    op.drop_column('custorder', 'note')
    op.drop_constraint(None, 'currentliability', type_='foreignkey')
    op.drop_constraint(None, 'currentasset', type_='foreignkey')
    op.drop_constraint(None, 'con_service_sale_item', type_='foreignkey')
    op.drop_constraint(None, 'con_service', type_='foreignkey')
    op.drop_constraint(None, 'con_service', type_='foreignkey')
    # ### end Alembic commands ###
